### ISSUE TITLE
TypeError: Cannot read property 'detect' of undefined

### ISSUE THREAD

**Issue by zhanghu11** [NSTiwari/TensorFlow.js-Custom-Object-Detection#1]
运行您的例子出现TypeError: Cannot read property 'detect' of undefined

**Comment by zhanghu11** [comment]
可以的话加我微信13033547336

**Comment by NSTiwari** [comment]
@zhanghu11, the error occurs because the code tries to detect the object(s) as soon as the web cam starts. Simply close the error and you'll find the detections.

**Comment by handamn** [comment]
im sorry, i have same issue here, but still get the detection after close the problem. Any suggestion? thankyou
