### ISSUE TITLE
issue in training

### ISSUE THREAD

**Issue by Gshubham101** [NSTiwari/TensorFlow.js-Custom-Object-Detection#3]
notimplementederror: cannot convert a symbolic tensor (cond_2/strided_slice:0) to a numpy array.
this error pops up when we run the code that contains model training, please help

**Comment by NSTiwari** [comment]
Hello, the error occurs due to incompatibility with the TF version. Downgrading the TF version to 2.3 should resolve the problem. Hope this helps.
